### ISSUE TITLE
US 06.01.01 As a user, I want a profile with a unique username (Wire to Main Activity)

### ISSUE THREAD

**Issue by EJ-Lan** [CMPUT301F23T28/CasaCatalog#32]
This is Finished Just Need To Be Wired To The Main Activity

**Comment by bottbott** [comment]
@EJ-Lan @jadc - noticing this crashing tonight. I merged in main recently while fixing a UI bug and entered in "Dave" for the user. Then tried to access the user profile page but it bugged out.

**Comment by jadc** [comment]
> @EJ-Lan @jadc - noticing this crashing tonight. I merged in main recently while fixing a UI bug and entered in "Dave" for the user. Then tried to access the user profile page but it bugged out.

Fixed in #57
